#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged
#docker-compose exec -T laravel.test php artisan test --testsuite=Feature --env=testing
#docker-compose exec -T laravel.test php artisan l5-swagger:generate
