#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '┌----------------------------------┐'
echo '¦     File verification started    ¦'
echo '└----------------------------------┘'

npx lint-staged

echo '┌----------------------------------┐'
echo '¦  File verification finished ✅   ¦'
echo '└----------------------------------┘'